# This sample Makefile, explains how you can compile plain AVR C file.
#
# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

NO_CORE = Yes

BOARD_TAG    = atmega32u4
MCU = atmega32u4
F_CPU = 16000000L

ISP_PROG   = usbasp

include ../../Arduino.mk
